ansforge/IG-fhir-repertoire-offre-ressources-sante

input/fsh/extensions/RORCalculatedDistance.fsh, input/fsh/extensions/RORContactFunctionContact.fsh, input/fsh/extensions/RORMetaCreationDate.fsh, input/fsh/extensions/RORTelecomCommunicationChannel.fsh, input/fsh/extensions/RORTelecomConfidentialityLevel.fsh, input/fsh/extensions/RORTelecomUsage.fsh, input/fsh/extensions/RORTerritorialDivision.fsh
Correction d'une erreur de syntaxe dans la définition du contexte des extensions
=> Correction syntaxe

input/fsh/instances/ror-sp-capacity-update-date.fsh
Correction d'une erreur dans le code du search parameter ror-capacity-update-date
=> Correction code SP

input/fsh/extensions/RORMetaCreationDate.fsh
Ajout de HealthcareService dans le context de l'extension RORMetaCreationDate
=> Ajout HealthcareService (context)

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/fsh/profiles/RORMeasure.fsh, input/fsh/profiles/RORMeasureReport.fsh, input/pagecontent/mapping.md
basé sur l'input dans le xls ci-joint
[profiling_Indicateurs_pilotage.xlsx](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/files/11732981/profiling_Indicateurs_pilotage.xlsx)
=> issue 55 ressources pour couvrir le cas d usage consultation d indicateurs de pilotage

input/pagecontent/specifications_techniques_3.md
cf https://www.hl7.org/fhir/R4/search.html#chaining
=> Correct url search spec technique 3

input/fsh/profiles/RORTask.fsh
permettre tous les types sur la slice "nouvelle valeur proposée"
@jcserafini voir preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/Permettre-tous-les-types-sur-la-slice-nouvelle-valeur-propos%C3%A9e/StructureDefinition-ror-task.html
=> Update RORTask.fsh suppression only string pour slice valeur proposee

input/fsh/profiles/RORHealthcareService.fsh
Pour valider cette PR nous avons besoin:
=> Improve notAvailable slice : date fermeture et date prévisionnelle de réouverture

input/fsh/profiles/RORHealthcareService.fsh
J'ai oublié de fixer la description
Est-ce que tu aurais des informations complémentaires sur les dates de fermeture et de réouverture @PhilippeC-ANS ? Par exemple la raison de la fermeture-réouverture pour adapter la description ?
=> Fix mandatory description to HealthcareService.notAvailable

input/fsh/profiles/ROROrganization.fsh
Suppression "type:fonctionLieu" dans ROR Organization qui en devait pas être présent.
=> ROROganization : Suppression "type:fonctionLieu"

.github/ISSUE_TEMPLATE/issue-bedmanagement.md
add template issue pour les éditeurs de solutions de bedmanagement
=> Update issue templates

input/fsh/profiles/RORLocation.fsh
ajout de Must support pour managingOrganization cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/94
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-MS-managingOrganization/StructureDefinition-ror-location.html
=> add MS managingOrganization

input/pagecontent/specifications_techniques_2.md, input/pagecontent/specifications_techniques_3.md, input/pagecontent/specifications_techniques_9.md
Cf #130 . 
correction de la syntaxe du iterate dans les requêtes exemples.
=> Correction syntaxe iterate

input/fsh/codesystems/RorIncludeAssociatedDataCodeSystem.fsh, input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/fsh/valueset/RorIncludeAssociatedDataVS.fsh, input/pagecontent/index.md, input/pagecontent/specifications_fonctionnelles.md, input/pagecontent/specifications_techniques_2.md, sushi-config.yaml
voici ma dernière itération à date.
N'hésitez pas à me proposer des corrections/modifs pour cette évolution encore au stade "expérimentale" sur l'IG.
Preview 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-bulk-data-import/specifications_fonctionnelles.html#sc%C3%A9narios-1
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-bulk-data-import/specifications_techniques_2.html#exemples-de-requ%C3%AAtes
=> add bulk data export

input/pagecontent/modifiers.md
Ajout uniquement dans le narratif le modificateur of-type.
=> Ajout modificateur of-type

input/pagecontent/search_param.md, input/pagecontent/specifications_techniques_4.md
Correction dans les requetes l'URL de la TRE_R330. 
Cf #164
=> Correction TRE_R330

input/fsh/profiles/RORPractitioner.fsh
voir issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/100
=> add system pour identifier PS

input/fsh/codesystems/ActTypeRORCodeSystem.fsh, input/fsh/extensions/RORActType.fsh, input/fsh/extensions/RORTerritorialDivision.fsh, input/fsh/profiles/RORHealthcareService.fsh, input/fsh/valueset/ActTypeRORValueSet.fsh, input/fsh/valueset/CodeRegionTerritorialDivisionRORValueSet.fsh
Ajout slice sur l'id dans le slice sur l'url pour les actes spécifiques et les actes hors cabinets
=> Sous Slice id acte specifique / acte hors cabinet

input/pagecontent/specifications_techniques_2.md, input/pagecontent/specifications_techniques_3.md, input/pagecontent/specifications_techniques_4.md, input/pagecontent/specifications_techniques_7.md, input/pagecontent/specifications_techniques_8.md
Correction des espaces en trop dans les exemples de requêtes
=> Correction typo espaces

input/pagecontent/specifications_fonctionnelles.md, input/pagecontent/specifications_techniques_1.md, input/pagecontent/specifications_techniques_3.md
Ajout scénario 1bis - Recherche sur une région
Retrait des Réponses simplifiées sur la page consultation des données capacitaires (plus de sens dans le format IG et uniformisation avec les autres pages)
Correction critère de recherche providedBy -> organization
=> 172 ajout scenarios ig

input/fsh/aliases.fsh, input/fsh/profiles/ROROrganization.fsh
proposition d'utiliser l'extension http://hl7.org/fhir/R4/extension-geolocation.html
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-extension-geoloc-orga/StructureDefinition-ror-organization.html
=> Sd add extension geoloc orga

input/pagecontent/index.md, input/pagecontent/securite.md, sushi-config.yaml
preview [sd-ig-securisation-transport](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-ig-securisation-transport/)
=> Sd ig securisation transport

input/pagecontent/specifications_techniques_7.md
correction erreur transcription docx vers IG sur scenario 2 consultation Ano
preview correction https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-correction-scenario-2-consultation-ano/specifications_techniques_7.html#sc%C3%A9nario-2-consultation-de-la-liste-des-anomalies
=> correction scenario 2 consultation Ano

input/fsh/extensions/RORConfidenceGeolocation.fsh, input/fsh/profiles/ROROrganization.fsh
changement :voir issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/213
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-confidence-geoloc/StructureDefinition-ror-organization.html
=> Sd add confidence geoloc dans extension geoloc

input/pagecontent/index.md, input/pagecontent/securite.md
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-lien-vers-me-v3/
=> add lien ME V3 et nouveau lien politique d'accès

input/fsh/codesystems/RorIncludeAssociatedDataCodeSystem.fsh, input/fsh/valueset/RorIncludeAssociatedDataVS.fsh
voir issue #287 
[lien preview](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-correctif-cs-include-associated-data) 
pour prévisualiser l'IG d'une branche
page https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-correctif-cs-include-associated-data/CodeSystem-ror-include-associated-data-code-system.html
aucun
=> correctif description code system

input/fsh/profiles/RORHealthcareService.fsh
correction typo RepoeningDate
cf issue #292 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-typo-closingRepoeningDate
ND
=> correction typo closingRepoeningDate

input/fsh/profiles/ROROrganization.fsh
Correction de la cardinalité de Organization.address : passage de 0..* à 0..1
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/274-cardinalite-organization-address
=> Correction cardinalité Organization.address

.github/workflows/a_release.yml, .github/workflows/a_tests_githubPages.yml
Ajout du lien vers la version @v0.1.0 du worklow des IG et ajout de la génération plantUML
Pas dans ce cas
Aucun
=> M priour patch 1

input/pagecontent/specifications_techniques_10.md
* Ajout requete Patch conditionnel
* Proposition warning pour la requete ajoutée
[https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/318-bedmanagement-patch-conditionnel/ig/specifications_techniques_10.html#bed-management-sc%C3%A9nario-9-remplacement-de-toutes-les-donn%C3%A9es-capacitaires-draft](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/318-bedmanagement-patch-conditionnel/ig/specifications_techniques_10.html#bed-management-sc%C3%A9nario-9-remplacement-de-toutes-les-donn%C3%A9es-capacitaires-draft)
Pas d'impact ?
=> #318 Bed Management

input/fsh/aliases.fsh, input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/pagecontent/index.md, input/pagecontent/modifiers.md, input/pagecontent/search_param.md, publication-request.json, sushi-config.yaml
cf issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/288
* mise à jour index
* mise à jour narratif tableau search param (suppression de draft)
* mise à à jour capability statements
- [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/[nom_de_la_branche] pour prévisualiser l'IG d'une branche](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-update-draft-ror-31/ig/index.html#informations-sur-ce-guide-dimpl%C3%A9mentation)
- 
- https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-update-draft-ror-31/ig/search_param.html
- https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-update-draft-ror-31/ig/modifiers.html
- https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sa …
=> modification pour mettre à jour IG par rapport à la maturité implémentation ROR 3.1 

.github/workflows/a_release.yml
* [changement 1]
* [changement 2]
* ...
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/[nom_de_la_branche] pour prévisualiser l'IG d'une branche
=> Update a_release.yml v0.2.0

input/pagecontent/specifications_techniques_3.md
Création du scénario 13 permettant de ramener les offres d’un professionnel à partir de son identifiant. 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/272-ajout-scenario-id-nat-ps/ig/specifications_techniques_3.html#sc%C3%A9nario-13-recherche-de-loffre-dun-professionnel
=> #272 Ajout d'un scénario de recherche de l'offre d'un professionnel avec un ID Nat PS

input/fsh/examples/RORQuestionnaireOffreDeVille.fsh, input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/fsh/profiles/RORQuestionnaire.fsh, input/fsh/valueset/RORUsageContextTypeVS.fsh, input/pagecontent/search_param.md
- modification code fixé erroné pour useContext PS => P01
- changement de placement du binding
- ajout dans les Capability statement pour questionnaire
- ajout draft pour les SP questionnaire dans le narratif search_params.md
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-corrections-questionnaire/ig/ pour prévisualiser l'IG d'une branche
changement code pour usecontext si dev commencé
=> Sd corrections questionnaire

input/fsh/profiles/RORQuestionnaire.fsh
* ajout de définitions en français supplémentaires
*  ajout de MS supplémentaires pour ce qui n'est pas en card min 1 dans la ressource Questionnaire
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-add_new-MS-questionnaire/ig/ pour prévisualiser l'IG de la branche
accès à la preview du profil https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-add_new-MS-questionnaire/ig/StructureDefinition-ror-questionnaire.html
prendre en compte les MS
=> Sd add new ms questionnaire

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/fsh/instances/ror-sp-healthcareservice-notavailable-closing-reopeningdate.fsh, input/pagecontent/search_param.md
voir issue #336
ajout sp sur HS
ajout dans Capability  Statement
ajout narratif
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-add-sp-sur-healthcareservice/ig/ pour prévisualiser l'IG de la branche
ajouter le nouveau SP
=> add sp notavailable-closing-reopeningdate

input/fsh/profiles/ROROrganization.fsh
ajout https pour être iso fr.core sur les system identifier orga
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-update-system-identifier-orga/ig/
pour prévisualiser l'IG de la branche
faible ?
changement url
=> Sd update system identifier orga

publication-request.json, release-notes.md, sushi-config.yaml
Préparation à la publication.
Documentation :
* https://fshschool.org/docs/sushi/configuration/
* https://confluence.hl7.org/display/FHIR/IG+Publication+Request+Documentation
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-prep-0-4-0-ballot1/ig/ pour prévisualiser l'IG d'une branche
Mise à dispo de la release ballot
=> preparation publication ballot

publication-request.json, release-notes.md, sushi-config.yaml
changement ballot -> qa-preview (frozen snapshot for non-ballot feedback)
* ...
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-modif-prep-publication-0-4-0-draft/ig/ pour prévisualiser l'IG d'une branche
=> add qa-preview label

input/images-source/creation_consignes_fiche-saisie.plantuml, input/images-source/recherche_consignes_fiche_saisie.plantuml, input/pagecontent/specifications_fonctionnelles.md
intégration dans la page specs fonctionnel de consignes fiche de saisie
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-update-spec-fonc/ig/specifications_fonctionnelles.html#consignes-fiche-de-saisie-de-loffre
Non
=> [Narratif]intégration dans la page specs fonctionnel de consignes fiche de saisie

input/pagecontent/downloads.md
* Précision sur la validation des ressources FHIR et le respect du standard
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/nr-add-usage/ig/downloads.html
Aucun, narratif, explicite le besoin déjà défini par le standard de le respecter pour assurer que les développeurs respectent les standards et le modèle de données indiqué dans l'IG
=> Mise à jour de la page téléchargement et usage

.github/pull_request_template.md, input/pagecontent/downloads.md, sushi-config.yaml
* mise à jour de l'index des pages (securité et download)
* mise à jour du pull request template (preview url)
Avant :
Après : cf preview
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/nr-update-menu/ig/downloads.html pour prévisualiser l'IG d'une branche
=> Mise à jour des pages pour avoir une numérotation cohérente

input/pagecontent/specifications_techniques_6.md
* correction du code et display dans le patch du scenario inactivation-anomalie
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-correction-scenario-inactivation-anomalie/ig/ pour prévisualiser l'IG de la branche
accès à la preview du scenario corrigé : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-correction-scenario-inactivation-anomalie/ig/specifications_techniques_6.html#scénario-2-inactivation-dune-anomalie
Non
=> Update scenario inactivation ano

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/pagecontent/consignes_fiche_saisie_offre.md, input/pagecontent/specifications_techniques_1.md, input/pagecontent/specifications_techniques_3.md
* voir issue #366 
* correction typo dans https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-suppr-draft-ror32/ig/consignes_fiche_saisie_offre.html
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/sd-suppr-draft-ror32/ig/ pour prévisualiser l'IG de la branche
NA
=> suppression draft pour les scenarios OK en 3.2 et adaptations suite à MEP ROR

input/pagecontent/search_param.md
add doc SP pour attribut du MEV3 typeOI
* ajout attribut OItype dans le tableau des SP de Orga
* ajout draft dans le tableau pour le SP 'type' pas développé dans ROR3.2 mais qui devrait l'être en 3.3
* ...
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/patch-doc-oitype/ig/search_param.html#structuredefinition-ror-organization
SP type non disponible dans ROR 3.2. A développer en 3.3
=> [Narratif] ajout attribut OItype dans le tableau des SP et ajout draft pour le SP 'type' pas encore développé en 3.2

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/pagecontent/miseAjour_offre.md, input/pagecontent/saisie_offre.md, input/pagecontent/specifications_techniques_10.md
retro specs suite à la MEP ROR 3.2
voir issue : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/373
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/patch-capability-statement-ror-32/ig pour prévisualiser l'IG d'une branche
=> Patch capability statement ror 3.2

input/pagecontent/consignes_fiche_saisie_offre.md, input/pagecontent/saisie_offre.md, input/pagecontent/specifications_techniques_10.md, input/pagecontent/specifications_techniques_5.md, publication-request.json, release-notes.md, sushi-config.yaml
préparation de la publication de la version 0.4.0
Status => à valider
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/prep-publication-040/ig pour prévisualiser l'IG d'une branche
=> preparation publication 0-4-0

input/fsh/instances/ror-serveur.fsh, input/pagecontent/consignes_fiche_saisie_offre.md
voir issue #395 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/add-put-questionnaire/ig pour prévisualiser l'IG d'une branche
Déjà développé et mis en prod
=> ouverture PUT pour questionnaire

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/pagecontent/search_param.md
voir issue #396 
- suppression de draft dans le tableau des SP
- décomment  SP type dans les instances CapabilityStatement
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/suppr-draft-sp-type-orga/ig pour prévisualiser l'IG d'une branche
Déjà développé et mis en prod
=> suppr draft et decomment dans CapabilityStatement

input/pagecontent/modifiers.md
voir issue #397
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/add-not/ig pour prévisualiser l'IG
Déjà développé et mis en prod
=> [narratif] ajout modifier not 

ig.ini
* [changement 1]
* [changement 2]
* ...
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/[nom_de_la_branche]/ig pour prévisualiser l'IG d'une branche
Aucun. Permettra d'accéder à la CI https://build.fhir.org/ig/ansforge/IG-fhir-repertoire-offre-ressources-sante/branches/main/
=> Maj du template pour permettre le déploiement sur build.fhir.org

input/fsh/instances/ror-consommateur.fsh, input/fsh/instances/ror-serveur.fsh, input/pagecontent/search_param.md
voir issue #394 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/SP-identifier-pract/ig pour prévisualiser les modifications
Aucun déjà en Prod
=> suppr draft et decomment dans Capability Statment pour le SP identifier pour practitioner et practitionerrole

input/pagecontent/index.md, publication-request.json, release-notes.md, sushi-config.yaml
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/prep-ig-ror33/ig pour prévisualiser l'IG d'une branche
=> Prep ig ror33

input/images-source/mapping-Organization.plantuml
voir issue #405 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/cp-map-uml-orga/ig pour prévisualiser l'IG d'une branche
Aucun
=> Update du mapping plantUML pour Organization

input/pagecontent/change-log.md, input/pagecontent/index.md, publication-request.json, sushi-config.yaml
préparation release 0.6.0
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/prep-release-0-6-0/ig pour prévisualiser l'IG d'une branche
=> prep-release-0-6-0

input/fsh/examples/RORQuestionnaireOffreDeVille.fsh, input/fsh/profiles/RORHealthcareService.fsh, input/images-source/mapping-HealthcareService.plantuml
HealthcareService.notAvailable : [0..*] -> [0..1]
\+ typo closingRepoeningDate
Aucun
=> CP : Fix : typo + cardinalité 0..1 HealthcareService.notAvailable
